### ISSUE TITLE
在npm仓库中搜索不到你的组件包？

### ISSUE THREAD

**Issue by zuoping1** [OceanPresentChao/Peintre#1]
为啥在npm仓库中找不到你的包呢？

搜索地址：https://www.npmjs.com/search?q=Peintre

是没有上传吗？这个组件挺好用的，可以上传一下吗？谢谢！

**Comment by OceanPresentChao** [comment]
最近没看github抱歉晚回复
本项目写的比较差难以使用，更像是一个应用而非组件，因此之前把npm包删除了。画板组件可参考仓库[OceanPresentChao/Peintre2](https://github.com/OceanPresentChao/Peintre2)，功能略有不同，组件样式功能可满足低要求的应用使用。看到你需要最近已发布到npm上，包名同样是peintre，详见[peintre](https://www.npmjs.com/package/peintre)
